### PR TITLE
Add multi-language support

### PR DESCRIPTION
**Pull request by qihangnet**
ai-shell-multi-languages

Although the default language is English, you have the option to select from the following languages.

- [x] Simplified Chinese
- [x] Traditional Chinese
- [x] Spanish
- [x] Japanese
- [x] Korean
- [x] French
- [x] German
- [x] Russian
- [x] Ukrainian
- [x] Vietnamese
- [x] Arabic
- [x] Portuguese

### CODE REVIEW

**Comment by steve8708** [comment]
Looks great @qihangnet! once build passes happy to merge and release

**Review by steve8708 — APPROVED** [review]

**Comment by qihangnet** [comment]
@steve8708 Sorry, I forgot to run 'npm run lint' for code checking before the last commit. It has been fixed now. Thank you for your understanding.

**Comment by steve8708** [comment]
No worries at all, this is amazing work!

**Comment by steve8708** [comment]
Released in version `0.1.20`!

**Pull request merged**
