### PR TITLE
Fix duplicated response

### PR DESCRIPTION
**Pull request by llagerlof**
This PR fix the issue #110

### CODE REVIEW

**Comment by mefengl** [comment]
It seems you accidentally included another commit from a different pull request in this pull request :)

**Comment by llagerlof** [comment]
Owner of this repository, about this PR, merge only the commit "Fix duplicated response" if you can.

**Comment by steve8708** [comment]
@llagerlof I don't know of an option to merge just the commit, I'll need you to remoce that commit (e.g. through a rebase)

e.g. 

```
git reset --hard HEAD~1
git push origin --force-with-lease
```

**Comment by steve8708** [comment]
also, thanks for the fix!

**Comment by llagerlof** [comment]
@steve8708 I will write more to fix this commit than the code itself. You can close this PR and make the fix (it's just one line), no problem for me.

Thanks!

**Comment by steve8708** [comment]
just pushed the fix, thanks @llagerlof !

**Pull request merged**
